local _M = {}

local hitloc = {
	[ "none" ]                        = 1,
	[ "helmet" ]                      = 1.25,
	[ "head" ]                        = 1.5,
	[ "neck" ]                        = 1.25,
	[ "torso_upper" ]                 = 1.1,
	[ "torso_lower" ]                 = 1,
	[ "right_arm_upper" ]             = 0.5,
	[ "left_arm_upper" ]              = 0.5,
	[ "right_arm_lower" ]             = 0.25,
	[ "left_arm_lower" ]              = 0.25,
	[ "right_hand" ]                  = 0.5,
	[ "left_hand" ]                   = 0.5,
	[ "right_leg_upper" ]             = 0.5,
	[ "left_leg_upper" ]              = 0.5,
	[ "right_leg_lower" ]             = 0.25,
	[ "left_leg_lower" ]              = 0.25,
	[ "right_foot" ]                  = 0.5,
	[ "left_foot" ]                   = 0.5,
	[ "gun" ]                         = 0.25
}

-- Shotgun damage is per pellet! on good hit alteast 5x that damage
local weapDmg = {
	[ "beretta_mp" ]                  = 28,
	[ "beretta_silencer_mp" ]         = 28,
	[ "colt45_mp" ]                   = 28,
	[ "colt45_silencer_mp" ]          = 28,
	[ "usp_mp" ]                      = 28,
	[ "usp_silencer_mp" ]             = 28,
	[ "deserteagle_mp" ]              = 55,
	[ "deserteaglegold_mp" ]          = 55,
	[ "mp5_mp" ]                      = 25,
	[ "mp5_reflex_mp" ]               = 25,
	[ "mp5_silencer_mp" ]             = 22,
	[ "mp5_acog_mp" ]                 = 25,
	[ "skorpion_mp" ]                 = 25,
	[ "skorpion_reflex_mp" ]          = 25,
	[ "skorpion_silencer_mp" ]        = 22,
	[ "skorpion_acog_mp" ]            = 25,
	[ "uzi_mp" ]                      = 25,
	[ "uzi_reflex_mp" ]               = 25,
	[ "uzi_silencer_mp" ]             = 22,
	[ "uzi_acog_mp" ]                 = 25,
	[ "ak74u_mp" ]                    = 28,
	[ "ak74u_reflex_mp" ]             = 28,
	[ "ak74u_silencer_mp" ]           = 25,
	[ "ak74u_acog_mp" ]               = 28,
	[ "p90_mp" ]                      = 18,
	[ "p90_reflex_mp" ]               = 18,
	[ "p90_silencer_mp" ]             = 14,
	[ "p90_acog_mp" ]                 = 18,
	[ "ak47_mp" ]                     = 30,
	[ "ak47_reflex_mp" ]              = 30,
	[ "ak47_silencer_mp" ]            = 28,
	[ "ak47_acog_mp" ]                = 30,
	[ "ak47_gl_mp" ]                  = 30,
	[ "m14_mp" ]                      = 30,
	[ "m14_reflex_mp" ]               = 30,
	[ "m14_silencer_mp" ]             = 28,
	[ "m14_acog_mp" ]                 = 30,
	[ "m14_gl_mp" ]                   = 30,
	[ "mp44_mp" ]                     = 35,
	[ "g3_mp" ]                       = 32,
	[ "g3_reflex_mp" ]                = 32,
	[ "g3_silencer_mp" ]              = 30,
	[ "g3_acog_mp" ]                  = 32,
	[ "g3_gl_mp" ]                    = 32,
	[ "g36c_mp" ]                     = 30,
	[ "g36c_reflex_mp" ]              = 30,
	[ "g36c_silencer_mp" ]            = 28,
	[ "g36c_acog_mp" ]                = 30,
	[ "g36c_gl_mp" ]                  = 30,
	[ "m16_mp" ]                      = 30,
	[ "m16_reflex_mp" ]               = 30,
	[ "m16_silencer_mp" ]             = 28,
	[ "m16_acog_mp" ]                 = 30,
	[ "m16_gl_mp" ]                   = 30,
	[ "m4_mp" ]                       = 35,
	[ "m4_reflex_mp" ]                = 35,
	[ "m4_silencer_mp" ]              = 30,
	[ "m4_acog_mp" ]                  = 35,
	[ "m4_gl_mp" ]                    = 35,
	[ "dragunov_mp" ]                 = 28,
	[ "dragunov_acog_mp" ]            = 28,
	[ "m40a3_mp" ]                    = 50,
	[ "m40a3_acog_mp" ]               = 50,
	[ "barrett_mp" ]                  = 28,
	[ "barrett_acog_mp" ]             = 28,
	[ "remington700_mp" ]             = 50,
	[ "remington700_acog_mp" ]        = 50,
	[ "m21_mp" ]                      = 28,
	[ "m21_acog_mp" ]                 = 28,
	[ "m1014_mp" ]                    = 10,
	[ "m1014_grip_mp" ]               = 10,
	[ "m1014_reflex_mp" ]             = 10,
	[ "winchester1200_mp" ]           = 10,
	[ "winchester1200_grip_mp" ]      = 10,
	[ "winchester1200_reflex_mp" ]    = 10,
	[ "rpd_mp" ]                      = 22,
	[ "rpd_acog_mp" ]                 = 22,
	[ "rpd_grip_mp" ]                 = 22,
	[ "rpd_reflex_mp" ]               = 22,
	[ "saw_mp" ]                      = 22,
	[ "saw_acog_mp" ]                 = 22,
	[ "saw_grip_mp" ]                 = 22,
	[ "saw_reflex_mp" ]               = 22,
	[ "m60e4_mp" ]                    = 22,
	[ "m60e4_acog_mp" ]               = 22,
	[ "m60e4_grip_mp" ]               = 22,
	[ "m60e4_reflex_mp" ]             = 22
}

local weaponclass = {
	[ "beretta_mp" ]                  = "pistol",
	[ "beretta_silencer_mp" ]         = "pistol",
	[ "colt45_mp" ]                   = "pistol",
	[ "colt45_silencer_mp" ]          = "pistol",
	[ "usp_mp" ]                      = "pistol",
	[ "usp_silencer_mp" ]             = "pistol",
	[ "deserteagle_mp" ]              = "pistol",
	[ "deserteaglegold_mp" ]          = "pistol",
	[ "mp5_mp" ]                      = "smg",
	[ "mp5_reflex_mp" ]               = "smg",
	[ "mp5_silencer_mp" ]             = "smg",
	[ "mp5_acog_mp" ]                 = "smg",
	[ "skorpion_mp" ]                 = "smg",
	[ "skorpion_reflex_mp" ]          = "smg",
	[ "skorpion_silencer_mp" ]        = "smg",
	[ "skorpion_acog_mp" ]            = "smg",
	[ "uzi_mp" ]                      = "smg",
	[ "uzi_reflex_mp" ]               = "smg",
	[ "uzi_silencer_mp" ]             = "smg",
	[ "uzi_acog_mp" ]                 = "smg",
	[ "ak74u_mp" ]                    = "smg",
	[ "ak74u_reflex_mp" ]             = "smg",
	[ "ak74u_silencer_mp" ]           = "smg",
	[ "ak74u_acog_mp" ]               = "smg",
	[ "p90_mp" ]                      = "smg",
	[ "p90_reflex_mp" ]               = "smg",
	[ "p90_silencer_mp" ]             = "smg",
	[ "p90_acog_mp" ]                 = "smg",
	[ "ak47_mp" ]                     = "rifle",
	[ "ak47_reflex_mp" ]              = "rifle",
	[ "ak47_silencer_mp" ]            = "rifle",
	[ "ak47_acog_mp" ]                = "rifle",
	[ "ak47_gl_mp" ]                  = "rifle",
	[ "m14_mp" ]                      = "rifle",
	[ "m14_reflex_mp" ]               = "rifle",
	[ "m14_silencer_mp" ]             = "rifle",
	[ "m14_acog_mp" ]                 = "rifle",
	[ "m14_gl_mp" ]                   = "rifle",
	[ "mp44_mp" ]                     = "rifle",
	[ "g3_mp" ]                       = "rifle",
	[ "g3_reflex_mp" ]                = "rifle",
	[ "g3_silencer_mp" ]              = "rifle",
	[ "g3_acog_mp" ]                  = "rifle",
	[ "g3_gl_mp" ]                    = "rifle",
	[ "g36c_mp" ]                     = "rifle",
	[ "g36c_reflex_mp" ]              = "rifle",
	[ "g36c_silencer_mp" ]            = "rifle",
	[ "g36c_acog_mp" ]                = "rifle",
	[ "g36c_gl_mp" ]                  = "rifle",
	[ "m16_mp" ]                      = "rifle",
	[ "m16_reflex_mp" ]               = "rifle",
	[ "m16_silencer_mp" ]             = "rifle",
	[ "m16_acog_mp" ]                 = "rifle",
	[ "m16_gl_mp" ]                   = "rifle",
	[ "m4_mp" ]                       = "rifle",
	[ "m4_reflex_mp" ]                = "rifle",
	[ "m4_silencer_mp" ]              = "rifle",
	[ "m4_acog_mp" ]                  = "rifle",
	[ "m4_gl_mp" ]                    = "rifle",
	[ "dragunov_mp" ]                 = "sniper",
	[ "dragunov_acog_mp" ]            = "sniper",
	[ "m40a3_mp" ]                    = "sniper",
	[ "m40a3_acog_mp" ]               = "sniper",
	[ "barrett_mp" ]                  = "sniper",
	[ "barrett_acog_mp" ]             = "sniper",
	[ "remington700_mp" ]             = "sniper",
	[ "remington700_acog_mp" ]        = "sniper",
	[ "m21_mp" ]                      = "sniper",
	[ "m21_acog_mp" ]                 = "sniper",
	[ "m1014_mp" ]                    = "shotgun",
	[ "m1014_grip_mp" ]               = "shotgun",
	[ "m1014_reflex_mp" ]             = "shotgun",
	[ "winchester1200_mp" ]           = "shotgun",
	[ "winchester1200_grip_mp" ]      = "shotgun",
	[ "winchester1200_reflex_mp" ]    = "shotgun",
	[ "rpd_mp" ]                      = "lmg",
	[ "rpd_acog_mp" ]                 = "lmg",
	[ "rpd_grip_mp" ]                 = "lmg",
	[ "rpd_reflex_mp" ]               = "lmg",
	[ "saw_mp" ]                      = "lmg",
	[ "saw_acog_mp" ]                 = "lmg",
	[ "saw_grip_mp" ]                 = "lmg",
	[ "saw_reflex_mp" ]               = "lmg",
	[ "m60e4_mp" ]                    = "lmg",
	[ "m60e4_acog_mp" ]               = "lmg",
	[ "m60e4_grip_mp" ]               = "lmg",
	[ "m60e4_reflex_mp" ]             = "lmg"
}

local weapClassFalloff = {
	[ "rifle" ]                       = 2200,
	[ "smg" ]                         = 1500,
	[ "shotgun" ]                     = 300,
	[ "lmg" ]                         = 1800,
	[ "sniper" ]                      = 6000,
	[ "pistol" ]                      = 1200
}

function _M.weaponDamage( weapon, damage, shitloc, distance )

	if weapDmg[ weapon ] == nil then
		return damage
	end
	
	local falloffMulti = 0.4
	local falloffMinDmg = 0.5
	
	local falloff = 1
	if distance > weapClassFalloff[ weaponclass[ weapon ] ] then
		falloff = 1 - ( ( distance / weapClassFalloff[ weaponclass[ weapon ] ] - 1 ) * falloffMulti )
		
		if falloff < falloffMinDmg then
			falloff = falloffMinDmg
		end
	end
		
	newdamage = math.floor( weapDmg[ weapon ] * hitloc[ shitloc ] * falloff )
	return newdamage
end

return _M